from enum import Enum
class PositionState(str, Enum): FLAT="FLAT"; LONG_RESIDUAL="LONG_RESIDUAL"; SHORT_RESIDUAL="SHORT_RESIDUAL"
class ResearchAction(str, Enum): WAIT="WAIT"; ENTER_LONG="ENTER_LONG"; ENTER_SHORT="ENTER_SHORT"; HOLD_LONG="HOLD_LONG"; HOLD_SHORT="HOLD_SHORT"; EXIT_LONG="EXIT_LONG"; EXIT_SHORT="EXIT_SHORT"; STOP_LONG="STOP_LONG"; STOP_SHORT="STOP_SHORT"; NO_SIGNAL="NO_SIGNAL"; CONFLICTED="CONFLICTED"; INSUFFICIENT_DATA="INSUFFICIENT_DATA"
